# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Author

# Model Form Field configuration
form: $/goosy/blog/models/author/fields.yaml

# Model Class name
modelClass: Goosy\Blog\Models\Author

# Default redirect location
defaultRedirect: goosy/blog/authors

# Create page
create:
    title: backend::lang.form.create_title
    redirect: goosy/blog/authors/update/:id
    redirectClose: goosy/blog/authors

# Update page
update:
    title: backend::lang.form.update_title
    redirect: goosy/blog/authors
    redirectClose: goosy/blog/authors

# Preview page
preview:
    title: backend::lang.form.preview_title
