# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/goosy/blog/models/category/fields.yaml

# Model Class name
modelClass: Goosy\Blog\Models\Category

# Default redirect location
defaultRedirect: goosy/blog/categories

# Create page
create:
    title: backend::lang.form.create_title
    redirect: goosy/blog/categories/update/:id
    redirectClose: goosy/blog/categories

# Update page
update:
    title: backend::lang.form.update_title
    redirect: goosy/blog/categories
    redirectClose: goosy/blog/categories

# Preview page
preview:
    title: backend::lang.form.preview_title
